name:                genotype
version:             0.1.0.0
github:              "kelvin-273/genotype"
license:             BSD3
author:              "Kelvin Davis"
maintainer:          "273degreeskelvin@gmail.com"
copyright:           "2022 Kelvin Davis"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kelvin-273/genotype#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  genotype-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genotype

tests:
  genotype-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genotype
