name:                gene-draw
version:             0.1.0.0
github:              "kelvin-273/gene-draw"
license:             BSD3
author:              "Kelvin Davis"
maintainer:          "273degreeskelvin@gmail.com"
copyright:           "2022 Kelvin Davis"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kelvin-273/gene-draw#readme>

dependencies:
- base >= 4.7 && < 5
#- diagrams >= 1.4
#- diagrams-tikz >= 0.6
- HaTeX
- optparse-applicative
- Hclip

library:
  source-dirs: src

executables:
  genedraw-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gene-draw

tests:
  genedraw-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gene-draw
    - hspec
